server:
  port: 10010
spring:
  application:
    name: dhand-gateway
  cloud:
    nacos:
      server-addr: 192.168.121.24:8848
    gateway:
      routes:
        - id: dhand-porta;
          uri: http://localhost:8081
          predicates:
            - Path=/portal/**